"""
A4 - fit the three classifiers and persist their test-set predictions.

Scope. This module FITS models and WRITES their predictions to disk. It does
not choose a winner, does not plot anything and does not tune a decision
threshold: A5 compares, A6 sets the threshold. Every number reported here is
taken at the default 0.5 cut, which is a placeholder and not a decision - a
point worth remembering before quoting any of these figures as final.

It also does not preprocess. The split is read from data/processed/ exactly as
A3 left it (deduplicated, see contract/A3_preprocessing_note.md). If those
files are missing this module stops and says so rather than regenerating them:
silently rebuilding the dataset would make the numbers in the A3 report and the
numbers here refer to two different datasets.

The three models, and why each is here:

  1. Random Forest        the main model.
  2. Logistic regression  the comparison model: does a linear decision surface
                          suffice, or is the extra capacity actually used?
  3. Fixed-rule baseline  the question the whole project has to answer -
                          why machine learning instead of a threshold?

Usage (from the repo root):
    python src/intelligence/train.py
"""

import argparse
import os
import sys
import time
import warnings

import joblib
import numpy as np
import pandas as pd
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.ensemble import RandomForestClassifier
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import (
    StratifiedKFold,
    cross_val_score,
    train_test_split,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.utils.validation import check_is_fitted

# Runnable as a script from the repo root as well as importable as a module.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from intelligence import contract  # noqa: E402
from intelligence.preprocess import (  # noqa: E402
    LABEL_COL,
    PROCESSED_DIR,
    Report,
    TARGET_COL,
    load_processed,
)

MODELS_DIR = "models"
REPORT_PATH = os.path.join("scripts", "scripts_output", "train_report.txt")
# Predictions live under data/, not models/: they are derived data, they are
# regenerated by this same command, and data/ is already gitignored whereas
# models/ only ignores *.pkl and *.joblib.
PREDICTIONS_PATH = os.path.join(PROCESSED_DIR, "test_predictions.parquet")

# Same seed as A3. The split, the CV folds and the forest all share it, so the
# whole chain from raw CSV to fitted model reproduces from one number.
RANDOM_STATE = 42

CV_FOLDS = 5
# Cross-validation runs on a stratified subsample, not on all 1.6M training
# rows. 5 folds x 3 models over the full set is roughly an hour of forest
# fitting to answer a question - "is this score stable or an artefact of one
# split?" - that 300k rows answer just as well. The FINAL models are fitted on
# the full training set; only the stability check is subsampled.
CV_SUBSAMPLE = 300_000

# lbfgs on 24 standardised features. Set high enough that non-convergence is a
# finding rather than the default outcome; the report states which it was.
LOGREG_MAX_ITER = 1000

RF_KEY, LR_KEY, BASE_KEY = "random_forest", "logistic_regression", "baseline_rule"

MODEL_FILES = {
    RF_KEY: os.path.join(MODELS_DIR, "random_forest.joblib"),
    LR_KEY: os.path.join(MODELS_DIR, "logistic_regression.joblib"),
    BASE_KEY: os.path.join(MODELS_DIR, "baseline_rule.joblib"),
}


# ---------------------------------------------------------------------------
# The one invariant that no metric can check for us
# ---------------------------------------------------------------------------

def assert_contract_order(X) -> None:
    """Fail loudly unless the columns are exactly FEATURES_24, in order.

    Position IS the contract. A permuted frame trains a model that reads
    `flow_duration` out of the slot holding `tot_fwd_pkts`; every metric in
    this report would still look entirely plausible, and the live extractor -
    which emits the correct order - would then hand the model a vector it has
    never seen. No accuracy number can detect that, so it gets an assertion.

    Parquet stores columns in write order and nothing in the format obliges a
    reader to return them that way. `load_processed()` does select by name, so
    on the normal path this always passes; it is here for the day someone
    builds X some other way, which is exactly when it will matter.
    """
    got = list(getattr(X, "columns", []))
    if got != list(contract.FEATURES_24):
        raise AssertionError(
            "feature columns are not in contract order.\n"
            f"  expected: {list(contract.FEATURES_24)}\n"
            f"  got:      {got}"
        )


# ---------------------------------------------------------------------------
# Model 3 - the fixed-rule baseline
# ---------------------------------------------------------------------------

class FixedRuleBaseline(BaseEstimator, ClassifierMixin):
    """The threshold rule that machine learning has to beat.

    WHY IT IS NOT "more than N connections in 10 seconds". The master document
    words the baseline that way, and that rule cannot be implemented in this
    component. Saying so precisely matters more than approximating it: the rule
    needs a per-source-IP counter with memory across flows, and this component
    is handed one finished flow at a time, with no IP (identity features are
    excluded from the contract as data leakage - A1 section 6.3) and no state
    between calls. That counter does exist in the system: it is the SOAR
    correlation that groups flows by source IP into one case. But it lives in
    component B, it is not a classifier, and it is not what A5 is comparing.

    THE HONEST TRANSLATION. One feature, one threshold: `flow_pkts_s`
    (position 21). Packets per second is the per-flow shadow of "connections
    per second" - the same intuition, measured on the only thing we can see.

    THE DIRECTION IS FITTED, NOT ASSUMED - and this was a finding, not a
    preference. The operational rule implies "high rate means attack", so that
    is the direction this class was first written with. Measured on the
    training set, that direction is worth F1 = 0.2861, while a classifier that
    labels EVERY flow an attack scores 0.2857: the rule as worded carries
    essentially no information on this data. The reason is visible in one
    line - median `flow_pkts_s` is 0.19 for attacks and 54.42 for benign
    traffic. The dataset's attacks are the SLOW flows, because a DoS holds
    connections open and a scan probe is one packet in a flow that then waits.

    So `fit` sweeps BOTH directions and keeps whichever scores better ON THE
    TRAINING SET, and the report prints both numbers. This is not the baseline
    being given the answer: no test row is involved, the rule still sees one
    feature, and a comparison against a strawman would prove nothing about
    machine learning. Reporting that the fixed rule is worthless because we
    aimed it backwards would be an artefact of our own wording, not a finding.

    NO predict_proba, DELIBERATELY. A threshold rule has no notion of
    confidence, therefore no ROC curve and no AUC. Manufacturing one by
    rescaling the feature would fabricate a curve the rule does not possess and
    would flatter it against models that genuinely produce one. A5 compares it
    on precision, recall and F1 alone.
    """

    def __init__(self, feature: str = "flow_pkts_s", n_candidates: int = 400):
        self.feature = feature
        self.n_candidates = n_candidates

    def _column(self, X) -> np.ndarray:
        """The one feature this rule looks at, from a frame or a raw array."""
        if hasattr(X, "columns"):
            return np.asarray(X[self.feature], dtype=np.float64)
        return np.asarray(X, dtype=np.float64)[
            :, contract.FEATURES_24.index(self.feature)
        ]

    def fit(self, X, y):
        """Pick the threshold that maximises attack-class F1 ON TRAINING DATA.

        Calibrating the cut on the test set would hand the baseline an
        advantage the other two models are not given, and the comparison A5
        makes would be worthless. The grid is quantiles of the training values,
        so the candidates follow the data's own distribution instead of an
        arbitrary linear range over a feature whose scale spans decades.
        """
        values = self._column(X)
        target = np.asarray(y)
        positive = target == contract.ATTACK
        n_positive = int(positive.sum())

        quantiles = np.linspace(0.0, 1.0, self.n_candidates)
        # method="lower" keeps every candidate an OBSERVED value. With a
        # `>=` rule the best threshold always coincides with one of the
        # observed values, so interpolating between them can only land in a
        # gap between two populations and miss the optimum that sits at the
        # edge of it - which is exactly the shape this data has.
        candidates = np.unique(np.quantile(values, quantiles, method="lower"))

        best = {"direction": ">=", "threshold": float(candidates[0]), "f1": -1.0}
        per_direction = {}

        for direction in (">=", "<="):
            direction_best = {"threshold": float(candidates[0]), "f1": -1.0}
            for threshold in candidates:
                predicted = (values >= threshold if direction == ">="
                             else values <= threshold)
                true_positive = int(np.count_nonzero(predicted & positive))
                n_predicted = int(np.count_nonzero(predicted))
                # F1 straight from the counts: 400 sweeps over 1.6M rows
                # through sklearn's f1_score would spend most of the time in
                # input validation.
                denominator = n_predicted + n_positive
                f1 = (2.0 * true_positive / denominator) if denominator else 0.0
                if f1 > direction_best["f1"]:
                    direction_best = {"threshold": float(threshold), "f1": f1}
            per_direction[direction] = direction_best
            if direction_best["f1"] > best["f1"]:
                best = {"direction": direction, **direction_best}

        self.classes_ = np.array([contract.BENIGN, contract.ATTACK])
        self.direction_ = best["direction"]
        self.threshold_ = float(best["threshold"])
        self.train_f1_ = float(best["f1"])
        # Kept so the report can show what the rule AS WORDED was worth, next
        # to what it is worth aimed the way the data actually points.
        self.direction_scores_ = per_direction
        self.n_candidates_ = int(len(candidates))
        self.n_features_in_ = X.shape[1]
        return self

    def predict(self, X) -> np.ndarray:
        check_is_fitted(self, "threshold_")
        values = self._column(X)
        flagged = (values >= self.threshold_ if self.direction_ == ">="
                   else values <= self.threshold_)
        return flagged.astype(np.int8)


# ---------------------------------------------------------------------------
# The three pipelines
# ---------------------------------------------------------------------------

def build_random_forest() -> Pipeline:
    """Estimator only, no scaler - and that is a decision, not an omission.

    A decision tree splits on the ORDER of a feature's values, never on their
    magnitude, so any monotone rescaling produces the identical tree. A
    StandardScaler here would cost a full pass over 1.6M rows to change
    nothing, and would add a fitted component that can go stale.

    Hyperparameters stay at sklearn's defaults on purpose: A4 is not a tuning
    task, and a tuned forest compared against an untuned baseline would not be
    the comparison A5 is asked to make.
    """
    return Pipeline([
        ("forest", RandomForestClassifier(
            # The imbalance treatment decided in A1 and deferred by A3 to here:
            # it is a model hyperparameter, so it belongs in the model, not in
            # a resampled copy of the training data.
            class_weight="balanced",
            random_state=RANDOM_STATE,
            n_jobs=-1,
        )),
    ])


def build_logistic_regression() -> Pipeline:
    """StandardScaler THEN LogisticRegression, both inside one Pipeline.

    Logistic regression is not scale-invariant: `flow_duration` reaches 1.2e8
    microseconds while `fwd_act_data_pkts` is a count in the single digits, and
    lbfgs on columns of that spread converges slowly and badly. So it needs the
    scaler. The question is where the scaler lives, and the answer is INSIDE
    the Pipeline, never fitted outside it, for two independent reasons:

    1. CROSS-VALIDATION. A scaler fitted on the whole training set before the
       folds are cut has already seen the rows it is about to be validated on:
       their mean and variance are baked into the transform, and the CV score
       comes back optimistic. Inside a Pipeline, sklearn refits the scaler on
       each training fold only, which is the sole correct order.

    2. SERIALISATION. joblib.dump on a bare estimator saves the coefficients
       and NOT the scaler. The model then loads without complaint and predicts
       with total confidence on unscaled live vectors - a silent failure, which
       is the class of failure this project documents as critical. A Pipeline
       is one object and cannot be separated from its own preprocessing.
    """
    return Pipeline([
        ("scaler", StandardScaler()),
        ("logistic", LogisticRegression(
            class_weight="balanced",
            random_state=RANDOM_STATE,
            max_iter=LOGREG_MAX_ITER,
        )),
    ])


def build_baseline() -> Pipeline:
    """Wrapped in a Pipeline so it goes through the identical evaluation code.

    Nothing to preprocess - a threshold on one raw feature is the whole model.
    The wrapper exists so that A5 cannot accidentally treat the baseline as a
    special case and evaluate it differently from the models it is judging.
    """
    return Pipeline([("rule", FixedRuleBaseline())])


# ---------------------------------------------------------------------------
# Evaluation helpers - measurement only, no comparison
# ---------------------------------------------------------------------------

def attack_scores(y_true, y_pred) -> dict:
    """Precision, recall and F1 of the ATTACK class. The benign class is the
    easy 83%; reporting its scores would flatter every model equally."""
    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, labels=[contract.ATTACK], zero_division=0
    )
    return {"precision": float(precision[0]),
            "recall": float(recall[0]),
            "f1": float(f1[0])}


def per_family_recall(labels, y_true, y_pred) -> pd.DataFrame:
    """Recall for each attack family, plus the benign false-positive rate.

    Recall is undefined for BENIGN in an attack-class framing, so that row
    reports the rate at which benign flows are called attacks instead. Both
    matter to the defence: a rule that catches everything by alarming on
    everything is not a detector.
    """
    frame = pd.DataFrame({"label": np.asarray(labels),
                          "y_true": np.asarray(y_true),
                          "y_pred": np.asarray(y_pred)})
    rows = []
    for name, group in frame.groupby("label", sort=False):
        flagged = float((group["y_pred"] == contract.ATTACK).mean())
        is_benign = group["y_true"].iloc[0] == contract.BENIGN
        rows.append({
            "family": name,
            "n": len(group),
            "metric": "false positive rate" if is_benign else "recall",
            "value": flagged,
        })
    return pd.DataFrame(rows).sort_values(
        ["metric", "n"], ascending=[True, False]
    ).reset_index(drop=True)


def stratified_subsample(X, y, labels, n: int, random_state: int):
    """A representative slice for the CV stability check.

    Stratified on the FAMILY string, not the binary target, for the same reason
    A3 split that way: PortScan is 0.10% of the data after deduplication, and a
    subsample stratified only on benign/attack could leave a fold with almost
    none of it.
    """
    if n >= len(X):
        return X, y
    X_sub, _, y_sub, _ = train_test_split(
        X, y, train_size=n, stratify=labels, random_state=random_state
    )
    return X_sub, y_sub


def cross_validate_f1(model, X, y) -> np.ndarray:
    """5-fold stratified CV on attack-class F1.

    n_jobs=1 on the outer loop: the forest already parallelises across all
    cores internally, and nesting the two oversubscribes them.
    """
    folds = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True,
                            random_state=RANDOM_STATE)
    return cross_val_score(model, X, y, cv=folds, scoring="f1", n_jobs=1)


# ---------------------------------------------------------------------------
# Persistence
# ---------------------------------------------------------------------------

def persist_model(path: str, name: str, pipeline: Pipeline, **extra) -> None:
    """Save the fitted Pipeline together with the contract it was trained on.

    The version travels WITH the model, in the same file, because the failure
    it prevents is a model built against one feature order being loaded by code
    that assumes another. Two files that must be kept in step would eventually
    fall out of step; one file cannot.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    joblib.dump({
        "name": name,
        "contract_version": contract.CONTRACT_VERSION,
        "features": list(contract.FEATURES_24),
        "pipeline": pipeline,
        "random_state": RANDOM_STATE,
        "trained_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        **extra,
    }, path)


def load_model(path: str) -> dict:
    """Load a model and refuse it if it does not match the current contract."""
    payload = joblib.load(path)
    if payload["contract_version"] != contract.CONTRACT_VERSION:
        raise ValueError(
            f"{path} was trained against contract "
            f"{payload['contract_version']}, this code is "
            f"{contract.CONTRACT_VERSION}. Retrain; do not override."
        )
    if payload["features"] != list(contract.FEATURES_24):
        raise ValueError(f"{path} was trained on a different feature order.")
    return payload


def persist_predictions(path: str, y_test, label_test, predictions: dict) -> None:
    """Write the test-set predictions so A5 never has to refit anything.

    A5 is a comparison task; it should read numbers, not spend twenty minutes
    reproducing them and risk reproducing them slightly differently.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    frame = pd.DataFrame({
        "y_true": np.asarray(y_test),
        LABEL_COL: np.asarray(label_test),
    })
    for key, values in predictions.items():
        frame[key] = values
    frame.to_parquet(path, index=False)


def load_predictions(path: str = PREDICTIONS_PATH) -> pd.DataFrame:
    """Read back what persist_predictions wrote. For A5."""
    return pd.read_parquet(path)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def _class_balance_line(rep: Report, name: str, y) -> None:
    y = np.asarray(y)
    n = len(y)
    n_attack = int((y == contract.ATTACK).sum())
    n_benign = n - n_attack
    rep(f"    {name:<12} {n:>12,}   BENIGN {n_benign:>12,} ({n_benign / n:6.2%})"
        f"   ATTACK {n_attack:>11,} ({n_attack / n:6.2%})")


def main() -> int:
    ap = argparse.ArgumentParser(description="A4: fit the three classifiers.")
    ap.add_argument("--processed-dir", default=PROCESSED_DIR)
    ap.add_argument("--models-dir", default=MODELS_DIR)
    ap.add_argument("--report", default=REPORT_PATH)
    args = ap.parse_args()

    for name in ("train", "test"):
        path = os.path.join(args.processed_dir, f"{name}.parquet")
        if not os.path.exists(path):
            raise SystemExit(
                f"{path} not found. A4 does not regenerate the dataset - "
                f"rebuilding it here would silently decouple these numbers "
                f"from the ones in the A3 report. Run:\n"
                f"    python src/intelligence/preprocess.py --drop-duplicates"
            )

    rep = Report()
    rep("A4 training report - three classifiers on the CICIDS2017 split")
    rep(f"contract version {contract.CONTRACT_VERSION}   "
        f"random_state={RANDOM_STATE}")
    rep("Threshold is the sklearn default 0.5 throughout. That is a")
    rep("placeholder, not a decision: A6 sets the operating point.")

    # ---- data ----------------------------------------------------------
    rep.banner("1. DATA")
    X_train, X_test, y_train, y_test, label_train, label_test = load_processed(
        args.processed_dir
    )

    # Before anything is fitted. See assert_contract_order().
    assert_contract_order(X_train)
    assert_contract_order(X_test)
    rep(f"feature columns verified against contract.FEATURES_24: "
        f"{contract.N_FEATURES} columns, in order")
    rep("")
    rep(f"    {'set':<12} {'rows':>12}")
    _class_balance_line(rep, "train", y_train)
    _class_balance_line(rep, "test", y_test)
    rep("")
    rep("Matches contract/A3_preprocessing_note.md section 3 (deduplicated")
    rep("dataset, decision D3). Nothing was re-preprocessed here.")

    # ---- cross-validation ----------------------------------------------
    rep.banner("2. CROSS-VALIDATION (stability check)")
    X_cv, y_cv = stratified_subsample(
        X_train, y_train, label_train, CV_SUBSAMPLE, RANDOM_STATE
    )
    rep(f"{CV_FOLDS}-fold stratified CV, scoring = F1 of the attack class")
    rep(f"subsample: {len(X_cv):,} of {len(X_train):,} training rows "
        f"({len(X_cv) / len(X_train):.1%}), stratified on the family label")
    rep("")
    rep("This is a deliberate time trade-off, stated rather than hidden: the")
    rep("question CV answers is whether a score is stable across splits, and")
    rep("300k rows answer it as well as 1.6M for a fraction of the cost. The")
    rep("FINAL models below are fitted on the FULL training set.")
    rep("")

    builders = {
        RF_KEY: ("Random Forest", build_random_forest),
        LR_KEY: ("Logistic regression", build_logistic_regression),
        BASE_KEY: ("Fixed-rule baseline", build_baseline),
    }

    cv_results = {}
    rep(f"    {'model':<24} {'mean F1':>10} {'std':>10}   folds")
    for key, (title, build) in builders.items():
        scores = cross_validate_f1(build(), X_cv, y_cv)
        cv_results[key] = scores
        rep(f"    {title:<24} {scores.mean():>10.4f} {scores.std():>10.4f}   "
            + " ".join(f"{s:.4f}" for s in scores))

    # ---- fit on the full training set ----------------------------------
    rep.banner("3. FIT ON THE FULL TRAINING SET")

    fitted, fit_seconds, notes = {}, {}, {}
    for key, (title, build) in builders.items():
        model = build()
        start = time.perf_counter()
        if key == LR_KEY:
            # Convergence is a finding, not an assumption. Capture the warning
            # rather than let it scroll past in the terminal.
            with warnings.catch_warnings(record=True) as caught:
                warnings.simplefilter("always", ConvergenceWarning)
                model.fit(X_train, y_train)
            converged = not any(
                issubclass(w.category, ConvergenceWarning) for w in caught
            )
            n_iter = int(model.named_steps["logistic"].n_iter_[0])
            notes[key] = (
                f"converged in {n_iter} of {LOGREG_MAX_ITER} iterations"
                if converged else
                f"DID NOT CONVERGE in {LOGREG_MAX_ITER} iterations "
                f"(n_iter={n_iter}) - treat its coefficients with suspicion"
            )
        else:
            model.fit(X_train, y_train)
        fit_seconds[key] = time.perf_counter() - start
        fitted[key] = model
        rep(f"    {title:<24} fitted in {fit_seconds[key]:>8.1f} s")
        if key in notes:
            rep(f"    {'':<24} {notes[key]}")

    rule = fitted[BASE_KEY].named_steps["rule"]
    rep("")
    rep("Baseline threshold, chosen on TRAINING data only:")
    rep(f"    rule:            {rule.feature} {rule.direction_} "
        f"{rule.threshold_:,.6f} -> ATTACK")
    rep(f"    how:             swept {rule.n_candidates_} distinct candidate")
    rep("                     thresholds, taken as quantiles of the training")
    rep("                     values (observed values, never interpolated),")
    rep("                     in BOTH directions, keeping the best attack F1")
    rep(f"    its train F1:    {rule.train_f1_:.4f}")
    rep("")
    rep("    Both directions, on training data:")
    for direction in (">=", "<="):
        score = rule.direction_scores_[direction]
        marker = "  <- kept" if direction == rule.direction_ else ""
        rep(f"        {rule.feature} {direction} {score['threshold']:>12.6f}"
            f"   F1 = {score['f1']:.4f}{marker}")
    constant_f1 = 2 * int((np.asarray(y_train) == contract.ATTACK).sum()) / (
        len(y_train) + int((np.asarray(y_train) == contract.ATTACK).sum())
    )
    rep(f"        (a classifier that flags EVERY flow scores {constant_f1:.4f})")
    rep("")
    rep("    The operational rule is worded 'more than N connections in 10")
    rep("    seconds', i.e. HIGH rate = attack. On this data that direction is")
    rep("    worth essentially nothing: it scores what a constant 'everything")
    rep("    is an attack' classifier scores. Median flow_pkts_s is 0.19 for")
    rep("    attacks and 54.42 for benign traffic - the dataset's attacks are")
    rep("    the SLOW flows, because a DoS holds connections open and a scan")
    rep("    probe is one packet in a flow that then waits. The direction is")
    rep("    therefore fitted on TRAINING data like the threshold, so that the")
    rep("    comparison in A5 is against the rule at its best and not against")
    rep("    a strawman of our own wording.")

    # ---- predict and score ---------------------------------------------
    rep.banner("4. ATTACK-CLASS SCORES ON TEST (threshold 0.5)")

    predictions, scores_test = {}, {}
    for key, (title, _) in builders.items():
        y_pred = fitted[key].predict(X_test)
        predictions[f"{key}_pred"] = np.asarray(y_pred, dtype=np.int8)
        scores_test[key] = attack_scores(y_test, y_pred)
        if hasattr(fitted[key], "predict_proba"):
            predictions[f"{key}_proba"] = fitted[key].predict_proba(X_test)[:, 1]

    rep(f"    {'model':<24} {'precision':>10} {'recall':>10} {'F1':>10}")
    for key, (title, _) in builders.items():
        s = scores_test[key]
        rep(f"    {title:<24} {s['precision']:>10.4f} {s['recall']:>10.4f} "
            f"{s['f1']:>10.4f}")
    rep("")
    rep("The baseline has no probability output by construction, so it has no")
    rep("ROC curve and no AUC. A5 must compare it on these three numbers only.")

    # ---- overfitting check ---------------------------------------------
    rep.banner("5. RANDOM FOREST: TRAIN vs TEST (overfitting check)")
    rf_train = attack_scores(y_train, fitted[RF_KEY].predict(X_train))
    rf_test = scores_test[RF_KEY]
    rep(f"    {'':<12} {'precision':>10} {'recall':>10} {'F1':>10}")
    rep(f"    {'TRAIN':<12} {rf_train['precision']:>10.4f} "
        f"{rf_train['recall']:>10.4f} {rf_train['f1']:>10.4f}")
    rep(f"    {'TEST':<12} {rf_test['precision']:>10.4f} "
        f"{rf_test['recall']:>10.4f} {rf_test['f1']:>10.4f}")
    rep(f"    {'gap':<12} {'':>10} {'':>10} "
        f"{rf_train['f1'] - rf_test['f1']:>10.4f}")
    rep("")
    rep("A forest with max_depth=None fits the training set almost perfectly by")
    rep("construction, so a gap here is expected and is not by itself evidence")
    rep("of a broken model. What matters is the size of the TEST number.")

    # ---- per-family recall ---------------------------------------------
    rep.banner("6. RECALL PER ATTACK FAMILY ON TEST")
    rep("The argument for machine learning over a fixed rule lives or dies")
    rep("here. Measured, not assumed.")
    rep("")
    tables = {k: per_family_recall(label_test, y_test, predictions[f"{k}_pred"])
              for k in builders}
    reference = tables[RF_KEY]
    rep(f"    {'family':<20} {'metric':<20} {'n':>9} "
        + "".join(f"{builders[k][0].split()[0]:>12}" for k in builders))
    for _, row in reference.iterrows():
        cells = ""
        for key in builders:
            table = tables[key]
            value = table.loc[table["family"] == row["family"], "value"].iloc[0]
            cells += f"{value:>12.4f}"
        rep(f"    {row['family']:<20} {row['metric']:<20} {row['n']:>9,}{cells}")

    # ---- persist --------------------------------------------------------
    rep.banner("7. PERSISTED")
    extra = {
        BASE_KEY: {"threshold": rule.threshold_, "feature": rule.feature,
                   "direction": rule.direction_},
    }
    for key, (title, _) in builders.items():
        path = MODEL_FILES[key] if args.models_dir == MODELS_DIR else os.path.join(
            args.models_dir, os.path.basename(MODEL_FILES[key])
        )
        persist_model(path, title, fitted[key],
                      cv_mean_f1=float(cv_results[key].mean()),
                      cv_std_f1=float(cv_results[key].std()),
                      fit_seconds=fit_seconds[key],
                      n_train_rows=len(X_train),
                      **extra.get(key, {}))
        rep(f"    {path:<44} contract {contract.CONTRACT_VERSION}")

    persist_predictions(PREDICTIONS_PATH, y_test, label_test, predictions)
    rep(f"    {PREDICTIONS_PATH:<44} {len(y_test):,} rows, "
        f"{len(predictions)} prediction columns + y_true + {LABEL_COL}")
    rep("")
    rep("Both models/*.joblib and data/ are gitignored. The reproducible")
    rep("artifact is this script plus the note, not the bytes on disk.")

    rep.banner("DONE")
    rep("Three models fitted. No winner chosen, no threshold tuned, nothing")
    rep("plotted - that is A5 and A6.")

    rep.save(args.report)
    print(f"\nreport saved to {args.report}")
    return 0


if __name__ == "__main__":
    # Re-enter through the package instead of calling main() directly.
    #
    # pickle stores a class by MODULE PATH, not by value. Running this file as
    # a script makes its module `__main__`, so a FixedRuleBaseline fitted here
    # would be written to models/ as `__main__.FixedRuleBaseline` - a name that
    # resolves in no other process. A5, the dashboard and the live IDS would
    # all fail to load the baseline with AttributeError, and only at load time.
    # Importing the module by its package name first means the estimator that
    # gets fitted and pickled is `intelligence.train.FixedRuleBaseline`, which
    # any process on this path can resolve.
    from intelligence.train import main as package_main

    sys.exit(package_main())
